### ISSUE TITLE
Rebuild java8 image

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/dockers#11]
PR #10, containing some changes to ``yegor256/java8`` has been merged. However, the build on DockerHub didn't happen yet (it should have been automatic...). 

Please rebuild the image manually so we can pull the new version from DockerHub.

**Comment by amihaiemil** [comment]
@yegor256 please take care of this asap...

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping, pls fix this, it's urgent and you can do it quickly

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@amihaiemil I'm planning to delete this repo. Please, use yegor256/rultor-image instead.

**Comment by amihaiemil** [comment]
@yegor256 sure, thanks for letting me know.
